close all;
voltage_raw = File_1096033O_SA03_W16_VT_MAX_SHIFTED.Data(1).Capture(4).Voltage;
voltage = lowpass(voltage_raw,0.0001);
current_raw = File_1096033O_SA03_W16_VT_MAX_SHIFTED.Data(1).Capture(4).Current;
current = lowpass(current_raw,0.0001);
time = File_1096033O_SA03_W16_VT_MAX_SHIFTED.Data(1).Capture(2).Time;
voltage_diff = diff(voltage);
time_diff = diff(time);
samplingFreq = 1 / mean(time_diff) * 2;
angularFreq = 2 * pi * samplingFreq;
voltage_deriv_raw = voltage_diff ./ time_diff;
% derivative = smooth(smooth(smooth(smooth(derivative_raw))));
voltage_deriv = lowpass(voltage_deriv_raw,0.001);
% Current
current_diff = diff(current);
current_deriv_raw = current_diff ./ time_diff;
current_deriv = lowpass(current_deriv_raw,0.0001);
figure(1);
plot(voltage);
yyaxis right;
plot(voltage_deriv);
figure(2);
clf;
plot(current); hold on;
yyaxis right;
plot(current_deriv);
thresh = max(current_deriv) * 0.8;
idx_shift = 15;
idx_shit_more = 10;
[peaksPos,peaksPos_idx] = findpeaks(voltage_deriv,'MinPeakHeight',thresh);
scatter(peaksPos_idx,peaksPos);
[peaksNeg_abs,peaksNeg_idx] = findpeaks(-voltage_deriv,'MinPeakHeight',thresh);
peaksNeg = -peaksNeg_abs;
scatter(peaksNeg_idx,peaksNeg);

yyaxis left;
accessVoltage1_idx = min(peaksNeg_idx) + idx_shift;
accessVoltage2_idx = max(peaksPos_idx) + idx_shift;
accessVoltage1 = voltage(accessVoltage1_idx);
accessVoltage2 = voltage(accessVoltage2_idx);
drivingVoltage1_idx = min(peaksPos_idx) - idx_shift - idx_shit_more;
drivingVoltage2_idx = max(peaksNeg_idx) - idx_shift;
drivingVoltage1 = voltage(drivingVoltage1_idx);
drivingVoltage2 = voltage(drivingVoltage2_idx);
idx_arr = [accessVoltage1_idx accessVoltage2_idx drivingVoltage1_idx drivingVoltage2_idx];
v_arr = [accessVoltage1 accessVoltage2 drivingVoltage1 drivingVoltage2];
scatter(idx_arr,v_arr,'Marker','*');